# -*- coding:utf-8 -*-

# A simple example using the HTTP plugin that shows the retrieval of a
# single page via HTTP. 
#
# This script is automatically generated by ngrinder.
#
# @author admin
from net.grinder.script.Grinder import grinder
from net.grinder.script import Test
from net.grinder.plugin.http import HTTPRequest
from net.grinder.plugin.http import HTTPPluginControl
from HTTPClient import NVPair

from HTTPClient import Cookie, CookieModule, CookiePolicyHandler
from org.json import JSONObject
import random, datetime, os, copy, logging, time
import com.xhaus.jyson.JysonCodec as json
from java.lang import System
from java.lang import Exception

#control = HTTPPluginControl.getConnectionDefaults()
# if you don"t want that HTTPRequest follows the redirection, please modify the following option 0.
# control.followRedirects = 1
# if you want to increase the timeout, please modify the following option.
#control.timeout = 6000

tests = {}
tests["1"] = Test(1, "getaid")
tests["2"] = Test(2, "login")
tests["3"] = Test(3, "createaccount")
tests["4"] = Test(4, "createcharacter")

tests["5"] = Test(5, "armor_levelup")
tests["6"] = Test(6, "armor_gradeup")
tests["7"] = Test(7, "armor_tireup")
tests["8"] = Test(8, "weapon_levelup")

tests["9"] = Test(9, "mission_modeinfo")
tests["10"] = Test(10, "mission_stageinfo")
tests["11"] = Test(11, "mission_start")
tests["12"] = Test(12, "mission_result")
tests["13"] = Test(13, "mission_result_sweep")

tests["14"] = Test(14, "overlord_list")
tests["15"] = Test(15, "overlord_start")
tests["16"] = Test(16, "overlord_result")

tests["17"] = Test(17, "shop_list")
tests["18"] = Test(18, "shop_item_buy")
tests["19"] = Test(19, "shop_buy_count_reset")
tests["20"] = Test(20, "shop_item_sell")
tests["21"] = Test(21, "shop_draw_gacha")

tests["22"] = Test(22, "goldexpedition_list")
tests["23"] = Test(23, "goldexpedition_set_group")
tests["24"] = Test(24, "goldexpedition_stage_info")
tests["25"] = Test(25, "goldexpedition_start")
tests["26"] = Test(26, "goldexpedition_result")

tests["27"] = Test(27, "test_itemmake")
tests["28"] = Test(28, "test_addexp")

# Make any method call on req increase TPS
urlbase = "http://14.63.226.42:11000/"

class TestRunner:
    account = None
    username = "bot_test_" + str(random.randint(10000, 20000))
    req = None # req = HTTPRequest()
    aid = None
    cid = None
    level = None
    acciteminven = None
    chariteminven = None
    activesoulinven = None
    passivesoulinven = None
    reterror = None
    testlist = []

    def GET(self, url, params = {}):
        global urlbase
        pairs = []
        for k, v in params.iteritems():
            pairs.append(NVPair(k, str(v)))

        pairs.append(NVPair("Debug", str("1")))
        # set cookie before REQUEST if we have
        #if self.cookies:
        #    for cookie in self.cookies:
        #        CookieModule.addCookie(cookie, HTTPPluginControl.getThreadHTTPClientContext())

        try:
            result = self.req.GET(urlbase + url, pairs)
        except Exception, e:
            grinder.logger.error("request Exception : " + e.strerror)
            raise e
        # set cookie after REQUEST if we had not
        #if not self.cookies and result.getStatusCode() == 200:
        #    self.cookies = CookieModule.listAllCookies(HTTPPluginControl.getThreadHTTPClientContext())

        return result

    def expect(self, substring, response, code=None):   
        assert response.getStatusCode() == 200, "response.getStatusCode(): " + repr(response.getStatusCode())
        try:
            js = json.loads(response.getText())
        except Exception, e:
            grinder.logger.error("response.text: " + str(response.text))
            raise e

        #if code and len(code) > 0:
        #   assert code in js["code"], pretty(js)
        #elif substring and len(substring) > 0:
        if substring and len(substring) > 0:
            grinder.logger.debug("EXPECTS SUBSTR: " + substring + "...")
        #    assert substring in js["message"], pretty(js)
        return js

    # initlialize a thread 
    def __init__(self):
        control = HTTPPluginControl.getConnectionDefaults() 
        control.timeout = 20000
        #grinder.logger.debug("%d %d / %d %d %d" % (self.totalProcessCount, self.totalThreadCount, grinder.agentNumber, grinder.processNumber, grinder.threadNumber))
        try:
            getparams = System.getProperty("param", "1");
            self.testlist = map(int, getparams.encode('utf-8').split(","))
            grinder.logger.info("testlist : " + str(self.testlist))
        except Exception, e:
            self.testlist.append(1)
            raise e
        grinder.statistics.delayReports=True
        pass
        #self.testlist.append(3)
        #self.user_login()

    def __del__(self):
        self.user_logout()

    # test method        
    def __call__(self):
       #totalThreadCount = grinder.getProperties().getInt("grinder.threads", 1);
       #self.aid = grinder.threadNumber + 1;
       #self.aid = random.randrange(2,6) # first eqaul or over, sencond under
       #self.aid = 5
        totalProcessCount = grinder.getProperties().getInt("grinder.processes", 1);
        totalThreadCount = grinder.getProperties().getInt("grinder.threads", 1);               
        self.username = "bot_%d_%08d" % (time.time(), (grinder.agentNumber * totalProcessCount * totalThreadCount) + (grinder.processNumber * totalThreadCount) + grinder.threadNumber)
        js = self.user_getaid();

        if js == None:
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
            return None

        self.user_login()
        if self.reterror == 40 or self.reterror == 1012:
            if self.reterror == 40:
                self.creat_account()                
                if self.reterror == 0:
                    self.create_character()
            elif self.reterror == 1012:
                self.create_character()

            grinder.logger.info("create_character reterror : %d" % (self.reterror))
            grinder.logger.info("testlist case : " + str(self.testlist))

            if self.reterror == 0:
                for testcase in self.testlist:
                    self.test_itemmake(testcase)
                    self.test_addexp()

            if self.reterror == 0:
                self.user_login()
                grinder.sleep(1000)

        for testcase in self.testlist:
            if testcase == 1:
                self.armor_test()
                self.mission_test()
            if testcase == 2:
                self.weapon_test()
                self.overlord_test()
            if testcase == 3:
                self.shop_test()
                self.goldexpedition_test()
            if testcase == 4:
                self.item_sell_test()
                self.gacha_test()

        return None

        #rnd = random.random()
        #if rnd < 0.3: js = self.building_get()
        #else: js = self.officer_list()

        #if js:
        #    grinder.statistics.forLastTest.success = 1
        #else:
        #    grinder.statistics.forLastTest.success = 0

    def test_itemmake(self, test_case=1):
        global tests
        self.req = HTTPRequest()
        tests["27"].record(self.req)

        if self.aid == None or self.aid == 0:
            return None
        if self.cid == None or self.cid == 0:
            return None

        makelist = []
        grinder.logger.info("test_itemmake test_case : %d" % (test_case))

        if test_case == 1:
            makelist.append({'itemid':303000001, 'makecount':1000000, 'makegrade':1})
            makelist.append({'itemid':303010001, 'makecount':128, 'makegrade':1})
            makelist.append({'itemid':303010102, 'makecount':80, 'makegrade':1})
            makelist.append({'itemid':303000002, 'makecount':300, 'makegrade':1})
        elif test_case == 2:
            makelist.append({'itemid':303000001,'makecount':5000000,'makegrade':1})
            makelist.append({'itemid':303040005,'makecount':2500,'makegrade':1})
            makelist.append({'itemid':303040007,'makecount':525,'makegrade':1})
            makelist.append({'itemid':303000003,'makecount':50,'makegrade':1})
        elif test_case == 3:
            makelist.append({'itemid':303000005,'makecount':10000,'makegrade':1})
            makelist.append({'itemid':303000001,'makecount':1000000,'makegrade':1})
            makelist.append({'itemid':303000015,'makecount':5000,'makegrade':1})
            makelist.append({'itemid':303000017,'makecount':5000,'makegrade':1})
            makelist.append({'itemid':303000018,'makecount':5000,'makegrade':1})
            makelist.append({'itemid':303000019,'makecount':5000,'makegrade':1})
            makelist.append({'itemid':303000020,'makecount':5000,'makegrade':1})
        elif test_case == 4:
            makelist.append({'itemid':303000005,'makecount':50000,'makegrade':1})
            makelist.append({'itemid':303000001,'makecount':5000000,'makegrade':1})
            makelist.append({'itemid':100030100,'makecount':10,'makegrade':2})
            makelist.append({'itemid':100030100,'makecount':10,'makegrade':3})
            makelist.append({'itemid':100030100,'makecount':10,'makegrade':5})
            makelist.append({'itemid':100030300,'makecount':10,'makegrade':2})
            makelist.append({'itemid':100030300,'makecount':10,'makegrade':4})
            makelist.append({'itemid':100030300,'makecount':10,'makegrade':5})
            #makelist.append({'itemid':303040007,'makecount':100,'makegrade':1})
            #makelist.append({'itemid':303040005,'makecount':100,'makegrade':1})
            #makelist.append({'itemid':303040012,'makecount':100,'makegrade':1})
            #makelist.append({'itemid':203030000,'makecount':100,'makegrade':1})
            #makelist.append({'itemid':303010003,'makecount':100,'makegrade':1})
            #makelist.append({'itemid':303010103,'makecount':100,'makegrade':1})

        js = None

        for makeitem in makelist:
            grinder.sleep(200)
            e = {'op': 'makeitem'}
            e['aid'] = self.aid
            e['cid'] = self.cid
            e['itemid'] = makeitem['itemid']
            e['makecount'] = makeitem['makecount']
            e['makegrade'] = makeitem['makegrade']
            r = self.GET('RequestItem.aspx', e)        
            js = self.expect(None, r)
            self.reterror = js['resultcode'];
            if self.reterror != 0:
                grinder.logger.info("test_itemmake reterror : %d" % (self.reterror))
                grinder.logger.error("request error")
                grinder.statistics.forLastTest.success = 0;
            else:
                grinder.statistics.forLastTest.success = 1
        return js

    def test_addexp(self, test_case=1):
        global tests
        self.req = HTTPRequest()
        tests["28"].record(self.req)

        if self.aid == None or self.aid == 0:
            return None
        if self.cid == None or self.cid == 0:
            return None

        e = {"op": "getexp"}
        e["aid"] = self.aid
        e["cid"] = self.cid
        e["exp"] = 123680   # for 40level set
        r = self.GET("RequestAccount.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];
        if self.reterror != 0:
            grinder.logger.info("test_addexp reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
            self.level = 41;
        return js

    def user_logout(self):
        grinder.logger.info("logged out : %d" % (self.aid))

    def user_getaid(self):
        global tests
        grinder.sleep(random.randrange(300,1000))

        self.req = HTTPRequest()
        tests["1"].record(self.req)
        e = {"op": "get_user_aid"}
        e["platform_type"] = 10000
        e["user_id"] = self.username
        r = self.GET("RequestPrivateServer.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror == 0:
            self.aid = js["aid"]
            grinder.statistics.forLastTest.success = 1
        else:
            grinder.logger.info("getaid reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        return js;

    def user_login(self):
        global tests
        self.req = HTTPRequest()
        grinder.sleep(200)
        tests["2"].record(self.req)

        if self.aid == None or self.aid == 0:
            return None
            
        e = {"op": "login"}
        e["aid"] = self.aid;
        #e = {"username": self.username, "password": self.password}
        #e["country"] = 1 if self.allies else 2
        #e["market_type"] = self.market_type
        #e["ssl"] = True
        #e["email"] = self.username + "@test.ee.com"

        r = self.GET("RequestAccount.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        grinder.logger.info("logged reterror : %d" % (self.reterror))

        if self.reterror == 0:
            self.account = js["account"]
            self.aid = self.account["aid"]
            self.cid = js["charactergroup"][0]
            self.level = js["characterlist"][0]["level"]
            self.acciteminven = js["accountinven"]
            self.chariteminven = js["characterinven"]
            #soullist = self.expect(None, js["soul_list"])
            for charsoul in js["soul_list"]:
                if charsoul["cid"] == self.cid:   
                    self.activesoulinven = charsoul["active_soul_list"]
                    self.passivesoulinven = charsoul["passive_soul_list"]
                    break
            grinder.logger.info("user_login in aid : %d" % (self.aid))
            grinder.logger.info("user_login in cid : %d" % (self.cid))
            #grinder.logger.info("user_login in characterinven : " + str(self.chariteminven))
            #grinder.logger.info("user_login in activesoulinven : " + str(self.activesoulinven))
            #grinder.logger.info("user_login in passivesoulinven : " + str(self.passivesoulinven))
        else:
            grinder.logger.info("user_login reterror : %d" % (self.reterror))

        grinder.statistics.forLastTest.success = 1
        return js

    def creat_account(self):
        global tests
        self.req = HTTPRequest()
        tests["3"].record(self.req)

        if self.aid == None or self.aid == 0:
            return None
        e = {"op": "createaccount"}
        e["aid"] = self.aid;        
        e["userid"] = self.username;
        e["username"] = self.username;        
        e["CountryCode"] = "kr";
        e["languagecode"] = 0;

        r = self.GET("RequestAccount.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];
        if self.reterror > 1900:
            grinder.logger.info("creat_account reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js


    def create_character(self):
        global tests
        self.req = HTTPRequest()
        tests["4"].record(self.req)

        if self.aid == None or self.aid == 0:
            return None
        e = {"op": "createcharacter"}
        e["aid"] = self.aid;
        e["class"] = random.randrange(1,3)

        r = self.GET("RequestAccount.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];
        self.cid = js["cid"];

        if self.reterror > 1900:
            grinder.logger.info("createcharacter reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js

    def armor_test(self):
        grinder.logger.info("armor_test start")

        armoritemlist = []
        for charitem in self.chariteminven:
            if charitem["equipposition"].find("Head") > 0:
                armoritemlist.append(charitem)
            elif charitem["equipposition"].find("Body")  > 0:
                armoritemlist.append(charitem)
            elif charitem["equipposition"].find("Hand")  > 0:
                armoritemlist.append(charitem)
            elif charitem["equipposition"].find("Foot") > 0:
                armoritemlist.append(charitem)

        for charitem in armoritemlist:
            for i in range(0,5):
                grinder.sleep(500)
                self.armor_levelup(charitem["invenseq"])
                if i < 4:
                    grinder.sleep(1000)
                    self.armor_gradeup(charitem["invenseq"])
                else:
                    grinder.sleep(1000)
                    self.armor_tireup(charitem["invenseq"])        
        return None


    def armor_levelup(self, invenseq, try_count = 5):
        global tests
        self.req = HTTPRequest()
        tests["5"].record(self.req)

        grinder.logger.info("armor_levelup invenseq : %d" % (invenseq))

        if self.aid == None or self.aid == 0:
            return None
        e = {"op": "enchantarmor"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["itemseq"] = invenseq;
        e["try_count"] = try_count;

        r = self.GET("RequestItem.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("armor_levelup reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js        

    def armor_gradeup(self, invenseq, try_count = 5):
        global tests
        self.req = HTTPRequest()
        tests["6"].record(self.req)

        grinder.logger.info("armor_gradeup invenseq : %d" % (invenseq))

        if self.aid == None or self.aid == 0:
            return None
        e = {"op": "evolutionarmor"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["itemseq"] = invenseq;

        r = self.GET("RequestItem.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("armor_gradeup reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js        

    def armor_tireup(self, invenseq, try_count = 5):
        global tests
        self.req = HTTPRequest()
        tests["7"].record(self.req)

        grinder.logger.info("armor_tireup invenseq : %d" % (invenseq))

        if self.aid == None or self.aid == 0:
            return None
        e = {"op": "metalworkarmor"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["itemseq"] = invenseq;

        r = self.GET("RequestItem.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("armor_tireup reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js


    def mission_test(self):
        grinder.logger.info("mission_test start")

        for i in range(1,11):
            grinder.sleep(2000)
            self.mission_start(i)
            grinder.sleep(15000)
            self.mission_result(i,1,0)

        for i in range(1,11):
            for j in range(0,4):
                grinder.sleep(2000)
                self.mission_result(i, 1, 1)
        return None

#tests["31"] = Test(31, "mission_modeinfo")
#tests["32"] = Test(32, "mission_stageinfo")
#tests["33"] = Test(33, "mission_start")
#tests["34"] = Test(340, "mission_result")

    def mission_info(self, stageid, worldid = 1):
        global tests
        self.req = HTTPRequest()
        tests["10"].record(self.req)
        grinder.sleep(1000)

        grinder.logger.info("mission_stage_info : %d-%d" % (worldid, stageid))

        if self.aid == None or self.aid == 0 or stageid == 0:
            return None

        e = {"op": "mission_taskinfo"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["worldid"] = worldid;
        e["stageid"] = stageid;

        r = self.GET("RequestMission.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("mission_stage_info reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js


    def mission_start(self, stageid, worldid = 1):
        global tests

        self.mission_info(stageid, worldid)

        self.req = HTTPRequest()
        tests["11"].record(self.req)

        grinder.logger.info("mission_start : %d-%d" % (worldid, stageid))

        if self.aid == None or self.aid == 0 or stageid == 0:
            return None

        e = {"op": "mission_start"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["worldid"] = worldid;
        e["stageid"] = stageid;

        r = self.GET("RequestMission.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("mission_start reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js


    def mission_result(self, stageid, worldid = 1, sweep = 0):
        global tests

        self.mission_info(stageid, worldid)
        self.req = HTTPRequest()

        if sweep == 0:
            tests["12"].record(self.req)
            grinder.logger.info("mission_result : %d-%d" % (worldid, stageid))
        else:
            tests["13"].record(self.req)
            grinder.logger.info("mission_result_sweep : %d-%d" % (worldid, stageid))

        if self.aid == None or self.aid == 0 or stageid == 0:
            return None

        e = {}
        if sweep == 0:
            e["op"] = "mission_result";
        else:
            e["op"] = "mission_result_sweep";

        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["worldid"] = worldid;
        e["stageid"] = stageid;
        e["cleartime"] = 15;
        e["clear"] = 1;

        r = self.GET("RequestMission.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            if sweep == 0:
                grinder.logger.info("mission_result reterror : %d" % (self.reterror))
            else:
                grinder.logger.info("mission_result_sweep reterror : %d" % (self.reterror))
                grinder.logger.error("request error")
                grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1

        return js


    def weapon_test(self):
        grinder.logger.info("armor_test start")

        weaponitem = None
        for charitem in self.chariteminven:
            if charitem["equipposition"].find("Weapon") > 0:
                weaponitem = charitem

        if weaponitem != None:
            for i in range(0,10):
                self.weapon_levelup(weaponitem["invenseq"])

        return None


    def weapon_levelup(self, invenseq):
        global tests
        grinder.sleep(1000)

        self.req = HTTPRequest()
        tests["8"].record(self.req)
        grinder.logger.info("weapon_levelup invenseq : %d" % (invenseq))

        if self.aid == None or self.aid == 0:
            return None
        e = {"op": "enchantweapon"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["itemseq"] = invenseq;

        r = self.GET("RequestItem.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("weapon_levelup reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js


    def overlord_test(self):
        global tests
        self.req = HTTPRequest()
        tests["14"].record(self.req)
        grinder.sleep(2000)

        grinder.logger.info("overlord_list : %d" % (self.aid))

        if self.aid == None or self.aid == 0:
            return None

        e = {"op": "overlord_list"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;

        r = self.GET("RequestOverlord.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror == 0:
            enemylist = js["overlord_lobby"]
            targetinfo = enemylist.pop()
            targetaid = targetinfo["aid"]
            targetisnpc = targetinfo["isnpc"]
            self.overlord_start(targetaid, targetisnpc)
            #grinder.logger.info("user_login in characterinven : " + str(self.charitemin
        
            if self.reterror == 0:
                self.overlord_result(targetaid, targetisnpc)

        if self.reterror > 1900:
            grinder.logger.info("overlord_list reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
     
        return js


    def overlord_start(self, targetaid, isnpc):
        global tests
        self.req = HTTPRequest()
        tests["15"].record(self.req)
        grinder.sleep(2000)

        grinder.logger.info("overlord_start : %d, isnpc %d" % (targetaid, isnpc))

        if self.aid == None or self.aid == 0 or targetaid == 0:
            return None

        e = {"op": "get_targetinfo"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["target"] = targetaid;
        e["isnpc"] = isnpc;

        r = self.GET("RequestOverlord.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("mission_start reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js


    def overlord_result(self, targetaid, isnpc):
        global tests
        self.req = HTTPRequest()
        tests["16"].record(self.req)
        grinder.sleep(10000)
        iswin = random.randrange(0,2)
        grinder.logger.info("overlord_result : %d, isnpc %d,. iswin %d" % (targetaid, isnpc, iswin))

        if self.aid == None or self.aid == 0 or targetaid == 0:
            return None

        e = {"op": "overlord_result"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["target"] = targetaid;
        e["isnpc"] = isnpc;
        e["iswin"] = iswin;

        r = self.GET("RequestOverlord.aspx", e)
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("mission_start reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js


    def shop_test(self):
        global tests

        if self.aid == None or self.aid == 0:
            return None

        self.req = HTTPRequest()
        tests["17"].record(self.req)
        grinder.sleep(3000)

        for shoptype in range(1,8):
            grinder.logger.info("shop_list : %d, shoptype : %d" % (self.aid, shoptype))
            e = {"op": "shop_list"}
            e["aid"] = self.aid;
            e["cid"] = self.cid;
            e["shoptype"] = shoptype;
            r = self.GET("RequestShop.aspx", e)        
            js = self.expect(None, r)
            self.reterror = js["resultcode"];

            if self.reterror > 1900:
                grinder.logger.info("shop_list reterror : %d" % (self.reterror))
                grinder.logger.error("request error")
                grinder.statistics.forLastTest.success = 0;    
            else:
                grinder.statistics.forLastTest.success = 1
                shopitemlist = js["shopitemlist"]
                for shopitem in shopitemlist:
                    itemid = shopitem["shop_item_id"]
                    if shoptype == 1:
                        if itemid > 106 :
                            self.shop_buy_item(shoptype, itemid)
                    else:
                        self.shop_buy_item(shoptype, itemid)

                if shoptype == 1:
                    trycount = 0;
                    while self.reterror == 0 and trycount < 10:
                        self.shop_buy_item(shoptype, 103, 5)  #buy gold 
                        trycount = trycount + 1;
                else:
                    self.shop_reset(shoptype)
                    for shopitem in shopitemlist:
                        itemid = shopitem["shop_item_id"]
                        self.shop_buy_item(shoptype, itemid)

        return js


    def shop_buy_item(self, shoptype, buyitemid, buycount = 1):
        global tests
        grinder.sleep(2000)

        self.req = HTTPRequest()
        tests["18"].record(self.req)

        grinder.logger.info("shop_buy_item shop_type : %d, buyitemid : %d" % (shoptype, buyitemid))

        if self.aid == None or self.aid == 0:
            return None
        e = {"op": "buy_shop_item"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["shop_item_id"] = buyitemid;
        e["buy_count"] = buycount;
        e["shoptype"] = shoptype;

        r = self.GET("RequestShop.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("shop_buy_item reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1

        return js


    def shop_reset(self, shoptype):
        global tests
        grinder.sleep(3000)

        self.req = HTTPRequest()
        tests["19"].record(self.req)

        grinder.logger.info("shop_reset shoptype : %d" % (shoptype))

        if self.aid == None or self.aid == 0:
            return None
        e = {"op": "shop_buy_count_reset"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["shoptype"] = shoptype;

        r = self.GET("RequestShop.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("shop_reset reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1

        return js


    def goldexpedition_test(self):
        global tests
        self.req = HTTPRequest()
        tests["22"].record(self.req)
        grinder.sleep(3000)

        grinder.logger.info("goldexpedition_list : %d" % (self.aid))

        if self.aid == None or self.aid == 0:
            return None

        e = {"op": "lobby"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;

        r = self.GET("RequestGE.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror == 0:
            enemylist = js["stage_info"]
            self.goldexpedition_setgroup()
            if self.reterror == 0:                
                for stageinfo in enemylist:
                    stageid = stageinfo["stage"]
                    self.goldexpedition_stage_info(stageid)
                    if self.reterror == 0:                
                        self.goldexpedition_start(stageid)
                        if self.reterror == 0:
                            self.goldexpedition_result(stageid)

        if self.reterror > 1900:
            grinder.logger.info("goldexpedition_list reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1

        return js


    def goldexpedition_setgroup(self):
        global tests
        self.req = HTTPRequest()
        tests["23"].record(self.req)
        grinder.sleep(1000)

        grinder.logger.info("goldexpedition_setgroup : %d" % (self.aid))

        if self.aid == None or self.aid == 0:
            return None

        e = {"op": "set_ge_group"}
        e["aid"] = self.aid;
        e["cid1"] = self.cid;

        r = self.GET("RequestGE.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("goldexpedition_setgroup reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1

        return js


    def goldexpedition_stage_info(self, stageid):
        global tests
        self.req = HTTPRequest()
        tests["24"].record(self.req)
        grinder.sleep(2000)

        grinder.logger.info("goldexpedition_stage_info stage : %d" % (stageid))

        if self.aid == None or self.aid == 0 or stageid == 0:
            return None

        e = {"op": "stage"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["stage"] = stageid;

        r = self.GET("RequestGE.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("goldexpedition_stage_info reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
       
        return js


    def goldexpedition_start(self, stageid):
        global tests
        self.req = HTTPRequest()
        tests["25"].record(self.req)
        grinder.sleep(10000)

        grinder.logger.info("goldexpedition_start stage : %d" % (stageid))

        if self.aid == None or self.aid == 0 or stageid == 0:
            return None

        e = {"op": "playstart"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["stage"] = stageid;
        e["bot"] = 1;

        r = self.GET("RequestGE.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("goldexpedition_start reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
        return js


    def goldexpedition_result(self, stageid):
        global tests
        self.req = HTTPRequest()
        tests["26"].record(self.req)
        grinder.sleep(1000)
        grinder.logger.info("goldexpedition_result : %d" % (stageid))

        if self.aid == None or self.aid == 0 or stageid == 0:
            return None

        e = {"op": "playresult"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["stage"] = stageid;
        e["bot"] = 1;

        r = self.GET("RequestGE.aspx", e)
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("goldexpedition_result reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
       
        return js


    def item_sell_test(self):
        global tests

        if self.aid == None or self.aid == 0:
            return None

        armoritemlist = []
        for charitem in self.chariteminven:
            if charitem["equipposition"].find("Head") > 0:
                armoritemlist.append(charitem)
            elif charitem["equipposition"].find("Body")  > 0:
                armoritemlist.append(charitem)
            elif charitem["equipposition"].find("Hand")  > 0:
                armoritemlist.append(charitem)
            elif charitem["equipposition"].find("Foot") > 0:
                armoritemlist.append(charitem)

        secondgradeitemlist = []
        thirdgradeitemlist = []
        fourthgradeitemlist = []
        fifthgradeitemlist = []

        for invenitem in self.acciteminven:
            if invenitem["grade"] == 2:
                secondgradeitemlist.append(invenitem["invenseq"])
            elif invenitem["grade"] == 3:
                thirdgradeitemlist.append(invenitem["invenseq"])
            elif invenitem["grade"] == 4:
                fourthgradeitemlist.append(invenitem["invenseq"])
            elif invenitem["grade"] == 5:
                fifthgradeitemlist.append(invenitem["invenseq"])

        seqlist = json.dumps(secondgradeitemlist);
        self.shop_item_sell(seqlist);
        seqlist = json.dumps(thirdgradeitemlist);
        self.shop_item_sell(seqlist);
        seqlist = json.dumps(fourthgradeitemlist);
        self.shop_item_sell(seqlist);

        for sellitem in fifthgradeitemlist:
            sellseq = []
            sellseq.append(sellitem)
            self.shop_item_sell(sellitem);

        return None


    def shop_item_sell(self, sellparam):
        global tests
        grinder.sleep(2000)

        self.req = HTTPRequest()
        tests["20"].record(self.req)

        grinder.logger.info("shop_item_sell itemseqs : %s" % (sellparam))

        if self.aid == None or self.aid == 0:
            return None
        e = {"op": "sellitem"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["sourceseq"] = sellparam;

        r = self.GET("RequestItem.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("shop_item_sell reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1
         
        return js


    def gacha_test(self):
        global tests

        if self.aid == None or self.aid == 0:
            return None

        for gachatype in range(1,5):
            for trycount in range(0,10):
                self.shop_draw_gacha(gachatype)

        return None


    def shop_draw_gacha(self, gacha_type):
        global tests
        grinder.sleep(2000)

        self.req = HTTPRequest()
        tests["21"].record(self.req)

        grinder.logger.info("shop_draw_gacha gacha_type : %d" % (gacha_type))

        if self.aid == None or self.aid == 0:
            return None
        e = {"op": "draw_gacha"}
        e["aid"] = self.aid;
        e["cid"] = self.cid;
        e["gacha_type"] = gacha_type;

        r = self.GET("RequestShop.aspx", e)        
        js = self.expect(None, r)
        self.reterror = js["resultcode"];

        if self.reterror > 1900:
            grinder.logger.info("shop_draw_gacha reterror : %d" % (self.reterror))
            grinder.logger.error("request error")
            grinder.statistics.forLastTest.success = 0;
        else:
            grinder.statistics.forLastTest.success = 1

        return js


