//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음
    // /str 옵션을 사용하여 ResGen을 다시 실행하거나 Visual Studio 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StringResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   공통 아이템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_allItem {
            get {
                return ResourceManager.GetString("lang_allItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_amount {
            get {
                return ResourceManager.GetString("lang_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_btn_add {
            get {
                return ResourceManager.GetString("lang_btn_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_btn_cancel {
            get {
                return ResourceManager.GetString("lang_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰 사용 중지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_btn_couponStop {
            get {
                return ResourceManager.GetString("lang_btn_couponStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_btn_creat {
            get {
                return ResourceManager.GetString("lang_btn_creat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_btn_remove {
            get {
                return ResourceManager.GetString("lang_btn_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_btn_search {
            get {
                return ResourceManager.GetString("lang_btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰코드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_couponCode {
            get {
                return ResourceManager.GetString("lang_couponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰 사용 중지일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_couponStopDate {
            get {
                return ResourceManager.GetString("lang_couponStopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰 1개 당 1인 사용(1:1)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_couponType1 {
            get {
                return ResourceManager.GetString("lang_couponType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰 1개 당 다수 사용(1:N)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_couponType2 {
            get {
                return ResourceManager.GetString("lang_couponType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_couponTypeSmall1 {
            get {
                return ResourceManager.GetString("lang_couponTypeSmall1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_couponTypeSmall2 {
            get {
                return ResourceManager.GetString("lang_couponTypeSmall2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이벤트명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_eventName {
            get {
                return ResourceManager.GetString("lang_eventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유효기간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_expirationDate {
            get {
                return ResourceManager.GetString("lang_expirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel 출력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_exportExcel {
            get {
                return ResourceManager.GetString("lang_exportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등급과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_grade {
            get {
                return ResourceManager.GetString("lang_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기간입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_inputDate {
            get {
                return ResourceManager.GetString("lang_inputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_item {
            get {
                return ResourceManager.GetString("lang_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   레벨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_level {
            get {
                return ResourceManager.GetString("lang_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   발행 개수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_makeCount {
            get {
                return ResourceManager.GetString("lang_makeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   발행 형태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_makeType {
            get {
                return ResourceManager.GetString("lang_makeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메모과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_memo {
            get {
                return ResourceManager.GetString("lang_memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   숫자만 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_msg_OnlyNumber {
            get {
                return ResourceManager.GetString("lang_msg_OnlyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   강무 아이템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_pc1Item {
            get {
                return ResourceManager.GetString("lang_pc1Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   월영 아이템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_pc2Item {
            get {
                return ResourceManager.GetString("lang_pc2Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   랑랑 아이템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_pc3Item {
            get {
                return ResourceManager.GetString("lang_pc3Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_regDate {
            get {
                return ResourceManager.GetString("lang_regDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_regGM {
            get {
                return ResourceManager.GetString("lang_regGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보상 아이템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_rewardItem {
            get {
                return ResourceManager.GetString("lang_rewardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   구분과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_separation {
            get {
                return ResourceManager.GetString("lang_separation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   무제한과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_unlimited {
            get {
                return ResourceManager.GetString("lang_unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쿠폰 사용자 수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lang_useCouponCount {
            get {
                return ResourceManager.GetString("lang_useCouponCount", resourceCulture);
            }
        }
    }
}
